[build]
  publish = ".next"
  command = "PUPPETEER_SKIP_DOWNLOAD=true npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  PUPPETEER_SKIP_DOWNLOAD = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
